### ISSUE TITLE
Int / Float Input Boxes

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#103]
We have a text input box but not an input box specifically for numbers

**Comment by david-vanderson** [comment]
This is a text input box with restrictions on what you can type in, right?  If so, the examples have one that does a filter - maybe we need a wrapping function that handles regularly used filters?

**Comment by VisenDev** [comment]
> This is a text input box with restrictions on what you can type in, right? If so, the examples have one that does a filter - maybe we need a wrapping function that handles regularly used filters?

Ideally we would have a function with a signature along the lines of
```zig
pub fn NumberEntryOptions(comptime T: type) type {
    return struct {
         min: T = std.math.intMin(T),
         max: T = std.math.intMax(T),
    };
};

pub fn numberEntry(src: std.builtin.SourceLocation, comptime T: type, result: *T, num_opts: NumberEntryOptions(T), dvui_opts: Options) !*NumberEntryWidget {}
```
