### ISSUE TITLE
missing common text box interactions

### ISSUE THREAD

**Issue by andrewrk** [david-vanderson/dvui#108]
* ctrl+backspace to delete previous word, ctrl+delete to delete next word
* ctrl+left to go back one word, ctrl+right to go forward one word
* home to go to beginning of line, end to go to end of line
* ctrl+home to go to beginning of all text, ctrl+end to go to end of all text
* double click to select word at cursor
* triple click to select line at cursor
* ctrl+A to select all

I'm sure there are more I'm forgetting but those are pretty frequently used, part of a lot of people's muscle memory.

Some of these require Unicode data awareness to implement correctly.

**Comment by david-vanderson** [comment]
Thanks for the feedback!  Yes you're right I'll get on implementing those.

I've been punting on Unicode support so far, so my plan for word-based stuff is just space delimited.  Do you need more than that?

**Comment by andrewrk** [comment]
Full disclosure, I don't have any current plans to use this project - I was just poking around on the web demo. Someday I'll be interested in an IMGUI for a digital audio workstation, but I haven't picked up that project in a long time.

**Comment by david-vanderson** [comment]
No problem, I appreciate the report regardless.

**Comment by david-vanderson** [comment]
These should all be working now, including double-click-drag and triple-click-drag.  They work with the corresponding key bindings on mac, even in the web demo.

Is this working for you now?

**Comment by andrewrk** [comment]
Nice, it's feeling a lot better! I did notice one more issue, if you select text in the middle starting from left to right and then press ctrl+right (or do the inverted version of this), the cursor is expected to go to the end of selection and become width 0 but instead it jumps to the end of the line.

**Comment by david-vanderson** [comment]
Well I'll be.  Never knew that before, and can't find any documentation for it, but you are totally right.  I've added that.

Anything else nobody ever told me?

**Comment by david-vanderson** [comment]
I believe this is fixed.  Please reopen or open another if needed.  Thank you!
