### ISSUE TITLE
Support using PgUp and PgDn for Scroll Widgets

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#110]
It would be nice if the page up and page down buttons could scroll a scroll area widget

**Comment by david-vanderson** [comment]
Good idea - I'll give it a shot.

**Comment by david-vanderson** [comment]
That seemed to work nicely.  Does it work for you?

**Comment by david-vanderson** [comment]
I think this got lost in the shuffle.  This should be working now - can you verify?

**Comment by VisenDev** [comment]
> I think this got lost in the shuffle. This should be working now - can you verify?

Yes it works, thanks! Sorry, my main laptop does not have PgUp/PgDn buttons so I wasn't able to test it immediately, and then I got distracted.
