### ISSUE TITLE
What is the file size after packaging?

### ISSUE THREAD

**Issue by qcjxberin** [david-vanderson/dvui#116]
What is the file size after packaging?

**Comment by david-vanderson** [comment]
Not sure exactly what you are looking for.  The size of the dvui dependency .tar.gz is around 2.5M.

Some statically compiled examples (compiled on osx):
web-test.wasm 10M
sdl-standalone 20M
raylib-standalone 12M

Does that answer your question?

**Comment by david-vanderson** [comment]
Forgot - those numbers are for debug builds.  For ReleaseFast:
web-test.wasm 6.3M
sdl-standalone 5.3M
raylib-standalone 4.5M
