### ISSUE TITLE
Tab character causes SDLBackend compile error

### ISSUE THREAD

**Issue by raddari** [david-vanderson/dvui#118]
zig version: `0.14.0-dev.1457+7e3180487`
dvui hash: `5be78609398c9f83f2c2dd87e63f239a017cddd7`

I followed the sdl-standalone example, but when building I receive the following error:
```
/home/<>/.cache/zig/p/1220733888d9c304e1e3476ab48698dad0ee3c137a94018adc8665a5dbfb81801c87/src/backends/SDLBackend.zig:132:17: error: expected statement, found 'invalid token'
                //*customization: -color
                ^~~~~~~~~~~~~~~~~~~~~~~~
```
This line and the next two contain tab characters. Replacing them with spaces fixes the issue.

**Comment by raddari** [comment]
Seems to be some breaking changes from `0.14.0-dev`. Can't pin the exact zig commit, but it seems hard tabs are a compile error now :)

**Comment by david-vanderson** [comment]
Closing this issue since the draft PR will take it from here.
