### ISSUE TITLE
Proposal: Remove globally mutable state from codebase

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#135]
Usage of global variables is widely regarded as an antipattern

“The road to programming hell is paved with global variables” – [Steve McConnell, Code Complete](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)

“Globals are responsible for all of the evil in the universe, from male pattern baldness to ozone depletion.” – Jack Ganssle, [Mars ate my spacecraft!](https://www.embedded.com/print/4215449)

I've developed a strong distaste for global variables (having had them bite me in the past). This is proposal is to remove global variables from the dvui codebase, and require all functions which previously accessed or mutated global state to *explicitly require state to be passed in via parameters*.

**Comment by david-vanderson** [comment]
Generally I agree, but sometimes they are more useful than not.  Is there a specific variable you want to change?

The main global variable in dvui is `current_window`, which is intentionally a global to support moving ui code from place to place without having to thread a `dvui.Window` to wherever you wanted to add some ui code.

**Comment by VisenDev** [comment]
There wasn't a specific global variable. I have just noticed a couple globals scattered around the code base (like `current_window`) and I wanted to bring up the issue. 

I agree globals can be convenient, its just not entirely clear to me what amount of convenience is worth the sacrifice of explicitly documenting which functions can mutate global state.

Perhaps the functional programmers have indoctrinated me too much haha

Although, the design of dvui does not require me to use global variables in my application codebase directly, so it may not really be a problem if dvui uses globals internally to simplify usage. I know raylib does the same thing and it doesn't seem to cause a problem for raylib.

I suppose for a library like dvui, the application is never really going to need more than one independant instance of the `current_window` - so its not quite as important for the `current_window` to always be a function parameter. In contrast to something like the lua c library, an application may want to keep track of several different lua states, so taking the lua state as an explicit parameter is more important

As for keeping track of which functions can mutate state, it is probably pretty obvious that functions like `dvui.button` are going to mutate ui state just from the function name.

**Comment by david-vanderson** [comment]
Makes sense!
