### ISSUE TITLE
weird arrow key handling in text selection for text entry

### ISSUE THREAD

**Issue by MichaelBelousov** [david-vanderson/dvui#160]
Behavior in most text controls I'm aware of, I'm specifically testing on the address bar of firefox
- pressing "left arrow key" while text is selected, removes the selection and places the cursor at the left side of the selection
- pressing "right arrow key" while text is selected, removes the selection and places the cursor at the right side of the selection

Behavior I'm seeing in dvui for `dvui.textEntry`:
- the cursor location is dependent on where you ended the selection, e.g. if you selected left to right, the cursor is at the right end of the selection, but if you dragged your selection right to left, you're at the left end
- ctrl-A (select all) doesn't move the text entry cursor
- pressing a key that doesn't end up moving the cursor (e.g. left after selecting everything right-to-left so the cursor is already at the leftmost index) while text is selected does nothing, selection is not removed
- pressing a key that does end up moving the cursor will move from where the last selection ended, and remove the selection

personally I find the "ctrl-A right/left" pattern which "moves the cursor to the start/end of the text entry" really useful in many applications so I think this is worth conforming

**Comment by david-vanderson** [comment]
Please reopen if that didn't fix it for you.  Thank you!
