### ISSUE TITLE
Build.zig: allow user to set raylib_linux_display 

### ISSUE THREAD

**Issue by Ziqi-Yang** [david-vanderson/dvui#161]
In my linux wayland machine, I haven't installed X11, so when I build the `raylib-standalone` example, the following error occurs:
```
/home/meowking/.cache/zig/p/122078aed9bcba3e2319105d04324bf923a52c65405c3662457cf73e7ef28f445e52/src/external/glfw/src/x11_platform.h:36:10: error: 'X11/Xcursor/Xcursor.h' file not found
#include <X11/Xcursor/Xcursor.h>
```
User should be able to set `raylib_linux_display` option so that they can set `raylib_linux_display` to `Wayland` to avoid this issue.

**Comment by david-vanderson** [comment]
Thanks for the report!

I've pushed a small commit so that we try "Wayland" unless we can't find a WAYLAND_DISPLAY environment variable.

Does that work for you?

**Comment by iacore** [comment]
Wait, this doesn't make sense. An application made with dvui should include both X11 and raylib backends and detect at runtime.

This issue is about building dvui without X11 support.

**Comment by david-vanderson** [comment]
Sorry sounds like I got this wrong.  When "Both", does raylib get compiled with x11 and wayland support and then chooses at runtime?

If so, then yes I should expose that build option.

**Comment by david-vanderson** [comment]
Okay committed a better fix.  The option "linux_display_backend" (same name as raylib's) is now exposed to the user.  If it's not given, build.zig will try to infer it based on the presence of WAYLAND_DISPLAY and DISPLAY environment variables.

Does that work?

**Comment by Ziqi-Yang** [comment]
Yes, it work! Thank you <3

**Comment by Ziqi-Yang** [comment]
> I still think that if it's not give, it should choose "Both" since that's a sensible choice for released applications.

Yes, I agree. The default option should be "Both" if user are in a Wayland environment. Only built for wayland display is a bit aggressive.

**Comment by david-vanderson** [comment]
I agree, but unfortunately raylib's build.zig bombs if it can't find the headers for both.  And it bombs early enough that you can't even do `zig build -h` to see what the options are.  Check me on this.

I think the true solution is to fix raylib's build.zig, but in the meantime we need `zig build` to not error (the user might not even care about raylib at that point).
