### ISSUE TITLE
Widget Request: File Input

### ISSUE THREAD

**Issue by Ziqi-Yang** [david-vanderson/dvui#163]
Thank you for your work on this awesome GUI library!

Just now I spent some time exploring this library and find that there is no File Input Widget.

From my understanding, a file input widget is a button that can call system file select dialog or uses our own. Example library: https://github.com/samhocevar/portable-file-dialogs

**Comment by david-vanderson** [comment]
You're welcome!  We have https://github.com/david-vanderson/dvui/issues/93 tracking this, and expect to use something exactly like that.
