### ISSUE TITLE
Demo example has blank thumbnails after window resize

### ISSUE THREAD

**Issue by Deins** [david-vanderson/dvui#167]
Both sdl examples, once window (os/backend one) gets resized, demo thumbnail images are gone:
![image](https://github.com/user-attachments/assets/7f9b3e09-9bde-4720-aaa5-e1b977311f67)
Seems cache/invalidation logic doesn't handle it. Can be repaired by clicking ui zoom or theme buttons which forces redraw.
Can be fixed with something like:
```zig
        const PrevWinSize = struct { // global variable
            var rect_pixels: dvui.Rect = dvui.Rect.all(-1);
        };
        const extern_resize = !PrevWinSize.rect_pixels.equals(dvui.currentWindow().rect_pixels);
        defer PrevWinSize.rect_pixels = dvui.currentWindow().rect_pixels;

        var invalidate: bool = extern_resize; // instead of original false
```
But probably could be done better, just started to look at this lib.

**Comment by david-vanderson** [comment]
Thanks for the report!  I'm having trouble reproducing it quickly, can you say what OS you are using?  And just to be sure, you are running `zig build sdl-standalone` and then resizing the OS window?

**Comment by Deins** [comment]
windows x64, amd gpu, latest main branch. Yes `zig build sdl-standalone` or sdl-ontop both.
As thumbnails themselves actually don't seem to change change size from window resizing, not actually sure what could be the reason they dissapear, but haven't investigated it in depth. 
Here is also video if it helps:
https://github.com/user-attachments/assets/e1755ae2-0e1a-4199-9b21-8fb149152e2a

**Comment by david-vanderson** [comment]
Thanks very much!  I'm able to reproduce it on my windows machine - it's very weird, and seems like maybe the texture memory is getting invalidated.  For me at least, sometimes the textures go blank, and sometimes they switch.

Will investigate.

**Comment by Deins** [comment]
Yeah, that seems likely, as everything else renders and responds ok, only those thumbnails.
Also managed to compile dx11 sample, it doesn't have this issue. 
But for my win11 machine needed additional linking `backend_mod.linkSystemLibrary("Ole32", .{});` to compile it.

By the way really cool library, much appreciated. Cheers.

**Comment by david-vanderson** [comment]
Thank you!

**Comment by Deins** [comment]
It looks like its sdl specific event: `SDL_RENDER_TARGETS_RESET` which resets all render textures as I understand.
My earlier comment that dx11 backend  works was not relevant - it just doesn't have render textures implemented yet so  its the same as running without CacheWidgets.
But from my understanding its old directx-9 feature to invalidate all render targets on resize, might be less of an issue for other backends or sdl3.

**Comment by david-vanderson** [comment]
Excellent sleuthing - thank you!

Based on that, it sounds like we have 2 options:
* A - Detect that event and invalidate caches
* B - Make CacheWidget copy out the pixels and put them into a new non-target texture

I'm leaning towards B as it doesn't introduce any new event handling, sound good?

**Comment by david-vanderson** [comment]
I've pushed a fix for this.  Thanks also for the ole32 tip - don't understand how I missed that before.

Is this fixed for you?

**Comment by david-vanderson** [comment]
Yep I agree.  Thank you!
