### ISSUE TITLE
Scroll bars on sdl-test main window

### ISSUE THREAD

**Issue by wilsonk** [david-vanderson/dvui#22]
When I start sdl-test on my Linux machine everything seems fine, but the 'floating window' button is not visible on the opening window. I have to grab the bottom of the window and enlarge it to see that there is a button at the bottom. I assume there should be a vertical scrollbar available when all the widgets don't fit into the current window? 

Or at least a minimum calculated size that requires the main window be large enough to show all currently 'visible' widgets? This option could lead to bad behavior, however, if a lot of widgets are on an opening page.

I think that a vertical scroll bar does pop up if a textentry widget is too large to contain in the main window (at least this happens in the example I am programming). So perhaps there is pre-existing checks/code that just needs to be used for other widget types?

**Comment by david-vanderson** [comment]
Sorry - sdl-test is kind of a sandbox I throw things into while I'm testing them.  I've cleaned it up so everything should fit.

I'm not sure if adding scrolling to a window by default is a good idea.  The 2 main examples (standalone-sdl and ontop-sdl) both have a scroll area inside the window, and I think that's the right way to go.  Do you agree?

**Comment by wilsonk** [comment]
Yes, the sdl-test example looks good now. I understand it is just a place to throw things for testing (which is why I am using it as a basis for my tests). The main window really should have a scroll bar on the side, but ONLY if the widgets force it to, in my opinion.

The 'show demo window' popup on the standalone example automatically pops up a scroll bar if you click the expanders and they expand below the bottom of the window. The main window should also do this, that is for sure...and it doesn't do this right now. I added the expanders to the sdl-test example and then click on them to expand them and they stick out the bottom of the main window without a scroll bar appearing. Now, if this 'main window' should never allow this behavior of expanding outside the window, or this sdl-test example code should never be used the way it is written, then that should be stated and/or not compile/run. Then, it should only be possible to put together a 'proper' example, like the standalone example or ontop example, and they will work this way (but I doubt this is the case that you are wanting).

A more controversial point, I guess, is whether the main window, upon opening, should have a scroll bar if all it's widgets don't fit on the opening main window. I say it should, and the example I am working on has this behavior because I have a very large textentry box upon opening (to display some code) and it is larger than the main window, when combined with all the other widgets. Because I am using a textentry widget, the scroll bar appears automatically, which is good. 

However, if my textentry (plus sundry other widgets) took up almost exactly the same size as the opening window, and then I added a few more buttons vertically, then they would not be shown on the opening window and there would be no scroll bar on the side to indicate that there were more widgets lower down below the viewable main window surface. This would be quite confusing for users, I think.

One can't guarantee that every user of a library will adhere to best practices and only put a small number of widgets on the opening page that are always on the viewable surface. Or the more likely case of someone using dynamic sizing of their main window, and not testing on a 780p display (or some 'lower than expected' resolution)...thus leading to widgets not appearing on the screen AND no scroll bar appearing, so the user can't expand the main window enough to even get to the other widgets! That is my worry with the current behavior. Sorry for the long winded response ;)

**Comment by david-vanderson** [comment]
I appreciate the thoughts!  You are totally right that sdl-test should have a scrollbar and I have added one.

I also played around with automatically adding a scrollbar to any main window and that didn't work as well.  sdl-test has a context menu that fills the whole window (and also uses an overlay that fills the whole window), and both of those don't work inside a scroll area when the window is big enough to show everything (because currently .expand inside a scroll area that scrolls in the same direction doesn't do anything - maybe that could be made better).

There's also the example "Direct Dialog" in the demo window that changes the size of a subwindow to fit the contents, which I'm not sure would make sense with a scrollbar.

So at least for now the scrollArea needs to be explicitly added if needed.  But you are right that the examples (including sdl-test) should have what we would recommend to start with.

**Comment by wilsonk** [comment]
Ok, thanks for the explanation. That is a little unfortunate that the context menu/overlay is restricting this. At least there is an option to add the scrollArea, as a solution. 

Not meaning to be a pain or anything...just putting in my two cents with this stuff :)  Perhaps others will feel strongly in one way or another, as well. Thanks for the quick updates.

**Comment by david-vanderson** [comment]
Not at all!  It's great that you are putting in the time to tell me what isn't working - very valuable information.  Thank you!
