### ISSUE TITLE
Obfuscation option for `TextEntryWidget`

### ISSUE THREAD

**Issue by r4gus** [david-vanderson/dvui#27]
It would be nice if users had the option to obfuscate the text displayed by the `TextEntryWidget`, e.g. the text `hello` is displayed as `*****`. 

Users would have to specify if the text should be obfuscated and what character to use for the obfuscation.

```zig
.obfuscate = .{
    .enable = true,
    .char = '*',
}
```

Keeping the cursor position in a valid state would be a bit of a challenge when translating between one and multi byte chars. This could crash the application when not done correctly. 

Asking for a password is a common scenario.

If this gets accepted I could implement a first draft.

**Comment by david-vanderson** [comment]
That would be wonderful!  I see you've already got a pull request going so I'll comment there.

**Comment by david-vanderson** [comment]
This is turning out to be quite hard, especially if we want to keep the obfuscated chars mapped to the underlying secret chars, so that selecting them, deleting, and inserting work properly.

I think the right place to make the switch is between TextEntryWidget and the TextLayoutWidget it uses internally.  I just need to figure out how to map the selection back and forth.

This also showed how invalid selection data can trip up TextLayoutWidget when that shouldn't be possible, so I'll think about that.

**Comment by r4gus** [comment]
If there was a unicode char of exactly one byte that would translate to something like `''` (no width) you could do something like the following:

```zig
if (self.init_opts.obfuscate != null and self.init_opts.obfuscate.?.enable) {
    const template: [4]u8 = .{ self.init_opts.obfuscate.?.char, '\u{?}', '\u{?}', '\u{?}' };
    var i: usize = 0;           
    while (i < self.len) {      
        const size = std.unicode.utf8ByteSequenceLength(self.init_opts.text[i]) catch 1;             
        try self.textLayout.addText(template[0..size], self.wd.options.strip());
        i += size;                                                                                   
    }                           
} else {                    
    try self.textLayout.addText(self.init_opts.text[0..self.len], self.wd.options.strip());          
}                           
try self.textLayout.addTextDone(self.wd.options.strip());
```

and keep the rest as is. There is the concept of a zero-width space but its encoded with more than one byte (https://en.wikipedia.org/wiki/Zero-width_space).

**Comment by david-vanderson** [comment]
Okay I committed something.  Under the basic widgets demo part there is a password entry box.  Can you please test it both with multibyte utf8 characters in the password, and also with a multibyte character for the .password_char?  (`.password_char = "€"` - as long as it's a single character)

Thanks!

**Comment by r4gus** [comment]
I'll check it out after work

**Comment by r4gus** [comment]
You can circumvent the check for the max input length.

The TextEntryWidget limits the input to 10 euro signs (`€`) but you can also enter 9 euro signs + one ascii char. If you do that you can add at least one extra euro sign. This will crash the application.

```zig
error: InvalidUtf8
/usr/local/bin/zig/lib/std/unicode.zig:231:13: 0x310881 in init (standalone-sdl)
            return error.InvalidUtf8;
            ^
/home/sugar/Projects/Test/dvui/src/dvui.zig:8157:27: 0x341ee3 in install (standalone-sdl)
            var utf8it = (try std.unicode.Utf8View.init(self.init_opts.text[0..self.len])).iterator();
                          ^
/home/sugar/Projects/Test/dvui/src/dvui.zig:8039:5: 0x345345 in textEntry (standalone-sdl)
    try ret.install(.{});
    ^
/home/sugar/Projects/Test/dvui/src/dvui.zig:9940:22: 0x349c3f in basicWidgets (standalone-sdl)
            var te = try dvui.textEntry(@src(), .{ .text = &text_entry_password_buf, .password_char = "*", .scroll_vertical = false, .scroll_horizontal_bar = .hide }, .{});
                     ^
/home/sugar/Projects/Test/dvui/src/dvui.zig:9838:13: 0x408d68 in demo (standalone-sdl)
            try basicWidgets();
            ^
/home/sugar/Projects/Test/dvui/standalone-sdl.zig:135:5: 0x40b3cd in dvui_frame (standalone-sdl)
    try dvui.examples.demo();
    ^
/home/sugar/Projects/Test/dvui/standalone-sdl.zig:45:9: 0x40f37a in main (standalone-sdl)
        try dvui_frame();
        ^
```

I guess that the widget considers each char to be exactly one byte when checking if there is enough space left.

**Comment by r4gus** [comment]
The same works with copy and paste.

Just copy 30 `a`s into the text box and then select one char and replace it with `€`. This will also crash the application.

**Comment by david-vanderson** [comment]
Aha - thanks so much for the testing and explanation!  I've pushed a fix, does that work for you?

**Comment by r4gus** [comment]
Looks good
