### ISSUE TITLE
SDL2 Missing; Build Issue on Windows 10

### ISSUE THREAD

**Issue by mochalins** [david-vanderson/dvui#29]
Hi! Just wanted to confirm that, from my understanding, the library is supposed to build and link SDL2 by itself? 

I'm currently on the latest update of Windows 10 using Zig version `0.12.0-dev.309+402468b21`. When I try to build the `dvui-demo` repository, I run into an issue that states: 
`error: unable to find Dynamic system library 'SDL2' using strategy 'paths_first'. searched paths: none`.

Is there any direction anyone can point me towards in resolving this issue?

Thank you!

**Comment by david-vanderson** [comment]
Sorry about that.  While the library eventually should build and link SDL2, it doesn't right now.  It's something I'm working on, but in the meantime do you need help building SDL2 separately?

**Comment by david-vanderson** [comment]
You might be in luck - I just committed adding a zig SDL dependency, and it at least works for me on Windows (but not Mac or Linux).  Does running `zig build sdl-test` work for you now?

**Comment by mochalins** [comment]
Oh wow! Sorry for the delayed response, but that's great to hear! I would love to test it on Windows, but sadly I'm not too familiar with GitHub and am unsure of how to find the link to the latest commit's archive. Do you happen to have the link on hand/know how I could look for it?
