### ISSUE TITLE
Horizontal scroll, using mouse wheel, pointer over content does not work.

### ISSUE THREAD

**Issue by JosephABudd** [david-vanderson/dvui#30]
# I really like dvui!

With horizontal scrolls, the wheel works when the carrot is positioned over the grab-bars, but not when the carrot is positioned over the content to be scrolled.

An example is at https://github.com/JosephABudd/okp.

The file at https://github.com/JosephABudd/okp/blob/main/src/okp/frontend/screen/tab/htabs/screen.zig constructs the horizontal scroll area at line 52.

If you run okp and go to  **htabs** from the main menu, you will see that I left the horizontal grab-bar under the tab-bar buttons.  The tab buttons scroll horizontally when the carrot is positioned over the horizontal grab-bar track and the mouse wheel is turned. The tab buttons do not scroll horizontally when the carrot is positioned over the buttons and the mouse wheel is turned.

I just cloned and ran the okp so I know that I pushed everything up there. BTW my tab-bar is added to the end of src/dvui/dvui.zig

**Comment by david-vanderson** [comment]
Thank you!  I'm very happy it's working for you.  I've committed a fix for the horizontal scrolling.

Separately, when I run okp and click a different tab (and am careful to not send any events after the mouse up), the new tab doesn't quite "settle" - the text areas are not the right height.  I think this is a bug in dvui, because they should notice that and cause a refresh automatically.  Looking into it...

**Comment by david-vanderson** [comment]
I'm only seeing this settling issue on my mac, and debugging statements seem to indicate the code is operating correctly.  So now I'm less sure it's a bug in dvui.  Maybe some kind of mac-specific issue somewhere.  Are you seeing this?

**Comment by JosephABudd** [comment]
Yes I noticed that with ubuntu. I click on the tab and the content is positioned lower from the top than it should be and then it's up where it should be.

**Comment by david-vanderson** [comment]
<img width="428" alt="Screen Shot 2023-09-16 at 3 16 17 PM" src="https://github.com/david-vanderson/dvui/assets/3290996/1e961abf-494c-4ea7-bd84-9988976d9437">

This is what I'm seeing - where there's too much space below the text, even though according to the code it's already refreshed.  Any further key press or mouse move causes a refresh and fixes it.  Is this the same thing you are seeing?

**Comment by JosephABudd** [comment]
I see something like that but only for a frame or 2.

**Comment by david-vanderson** [comment]
Okay that is normal.  A recent change to dvui helped make the visual change less bad (stuff about the default width of TextLayoutWidget).  Seems like there is some issue that's only affecting my mac.

Does the mouse wheel now scroll horizontally for you?

**Comment by JosephABudd** [comment]
I'll check, this will take a few minutes. :)

**Comment by JosephABudd** [comment]
Not over the content (the tabs) only over the grab bar.

**Comment by JosephABudd** [comment]
I did that incoreectly. I may work but I don't know yet becuase Ive got some errors in my own code.

**Comment by JosephABudd** [comment]
Ok, this will take a while. I'll have to get back with you as I'm about to leave. :) I can see i need to make several changes. :)

**Comment by JosephABudd** [comment]
Yes, they both scroll using the mouse wheel with or without the grab-bars.

**Comment by JosephABudd** [comment]
Nice work.
