### ISSUE TITLE
Change "@fabs" to "@abs".

### ISSUE THREAD

**Issue by JosephABudd** [david-vanderson/dvui#41]
dvui/src/dvui.zig
dvui/src/tinyvg/rendering.zig
dvui/sdl-test.zig

I'm checking. I think my version of zig is a week old. I'll download today's version. and recheck.

**Comment by JosephABudd** [comment]
My mistake.

**Comment by david-vanderson** [comment]
Is @abs new after zig 0.11.x?  I don't have a plan for when to switch, but I assume that at some point we'll have to switch from stable to following zig master again.

Do you have a sense for what other zig projects are doing?
