### ISSUE TITLE
href/ url object

### ISSUE THREAD

**Issue by r4gus** [david-vanderson/dvui#44]
I think it would be nice to have a href/ url object that is a combination of label and button (but without the styling of a button). The expected behavior would be that dvui opens the url  using the default browser on click.

Something like:
```
dvui.href("Text to display", "https://github.com/david-vanderson/dvui");
```

**Comment by david-vanderson** [comment]
That is a good idea!  Looks like SDL has a function to open a URL, so that functionality might already be there.

Probably we'd want that functionality in multiple places, and I'm trying to figure out how to split it.

Thinking through it:
* label already has options for styling text (so can choose to show for example blue text)
  * eventually need options to add underlining (and strikethrough)
* we can already set the cursor

Probably can wrap that stuff up in a function to give you most of what you are looking for.

But also we probably want a way to integrate this kind of thing into textLayout, so part of the text could be a hyperlink.  I'll dig into that.

Thanks very much!

**Comment by david-vanderson** [comment]
Turns out we already had almost everything needed.  I've added a new function `labelClick()` that works just like `label()` but returns if it got clicked.  Check it out in the Basic Widgets part of the demo!

**Comment by r4gus** [comment]
![Screenshot from 2023-11-01 21-22-13](https://github.com/david-vanderson/dvui/assets/25912761/a04441c3-410b-4f76-90ff-5cd7b0ab1208)

Thanks! Works perfectly :)

**Comment by david-vanderson** [comment]
That is so cool!  I've been wondering about PassKeys for a while, and now I get to dig into your keylib and keypass stuff.  Thank you!

PS - I saw in a brief look that you also need a way to trigger a refresh from outside the normal begin/end sequence.  I'm hitting that issue and will address it.

**Comment by r4gus** [comment]
Thanks 👍 a refresh would be super helpful, otherwise the confirmation dialog doesn't pop up automatically.

**Comment by r4gus** [comment]
Btw if you have questions/ want to know something specific don't hesitate to ask

**Comment by david-vanderson** [comment]
Thanks very much!  I've added refreshing from other threads, and adding a dialog automatically calls refresh.  Does that solve that issue for you?

**Comment by r4gus** [comment]
![ezgif com-video-to-gif](https://github.com/david-vanderson/dvui/assets/25912761/659809ab-b776-48b3-a084-1f3ef322fb6d)

Looks pretty good! The dialog is now instantly shown.

**Comment by david-vanderson** [comment]
That is awesome!

I'm rewatching your talk [Implementation of a FIDO2 Authenticator Library in Zig](https://www.youtube.com/watch?v=UOaumWJSKgQ) at Software You Can Love VC 2023.  After reading the QA at https://github.com/r4gus/keylib, I'm still unclear on the difference between CTAP2 and Webauthn.  I would love an extra entry in the QA for this.  Is webauthn only a browser thing?  Is there a scenario where Webauthn is not used (maybe a local application that you log into)?

**Comment by r4gus** [comment]
The fido2 protocol involves 3 entities: the authenticator, a client (e.g. web browser) and a relying party (e.g. github authentication server). Ctap2 is the protocol that handles communication between authenticator and client. Webauthn is a standard that defines a somewhat abstract API between client and relying party.

**Comment by r4gus** [comment]
I gonna make an additional QA entry 👍

**Comment by david-vanderson** [comment]
Ah thank you that helps so much.  Now that I'm going through your talk again, I realize you answered that question, so sorry for the repeated questions, and thanks for adding it to the QA.  Thanks for patiently helping me get up to speed on it!

**Comment by r4gus** [comment]
Happy to help. A lot of people use webauthn, fido2 and passkey interchangeably which makes it pretty confusing.

**Comment by david-vanderson** [comment]
Would you mind if I link to your project from the dvui readme?  https://github.com/david-vanderson/dvui at the top of the readme.  If it's okay, is that the right name and link?  Thanks!

**Comment by r4gus** [comment]
It's absolutely ok, thanks!

**Comment by david-vanderson** [comment]
I finally added TextLayoutWidget.addTextClick() so text layout also has this functionality.

Please reopen this if you see any problems.  Thanks!
