### ISSUE TITLE
Feature request: float/vector draggable text field

### ISSUE THREAD

**Issue by KnockerPulsar** [david-vanderson/dvui#45]
Hello, thanks for the work on this library so far!

I think the inclusion of some float/vector widgets might be a big boon to the library in terms of ease of use. What I'm aiming for is something similar to ImGui's `SliderFloat` (correct me if I'm wrong), where you pass in some floats, and the data is updated as you drag or modify the text field. This would mix the functionality of sliders and text fields, with the added bonus of perhaps not needing a min/max like a real slider, just some increment speed. 

So it would be something like:
```zig
const foo = @Vector(3, f32) { 420, 1337, 0 };
dvui.sliderFloat(@src(), f32, 3, &foo, ..); 
```
Where `..` denotes any extra needed parameters (init options and so on).

Forgive me if I got some details wrong, can't quite fire up ImGui's demo right now. I also understand if you're not interested in emulating ImGui. If so, feel free to close this issue.

**Comment by david-vanderson** [comment]
Thank you!

That is a good idea.  I looked at ImGui's slider float and how it works - they have it mode switch to text input when you ctrl-click (or double-click for SliderFloat).  I'm thinking instead we could mode switch on any key event.

They also distinguish between a SliderFloat (has a min/max, single click sets the value) and a DragFloat (optional min/max, only dragging changes the number).  Maybe we can combine them somehow (if you give min/max, do the slider thing, otherwise do the drag?).

There are a lot of details to get right, so it'll take a few iterations of testing.  Maybe we can use zig comptime to automatically handle both floats and ints depending on the type of pointer passed in?

I'll start with a single float, and post again when there's something to test.  Thanks!

**Comment by KnockerPulsar** [comment]
Thanks a lot! I wanted to put together a prototype before posting the issue, but got a bit intimidated by the source code of the library. I'll be closely following your works so I perhaps get to help later on :)

**Comment by david-vanderson** [comment]
Totally understand, and that's something that needs to be improved.  What can be done to make it more approachable?  Is the primary barrier lack of high-level docs talking about how things are put together?  Or is it more lack of source-level comments?  Something else?  Any feedback would be very useful, because it's hard for me to see it with fresh eyes.  Thanks!

**Comment by KnockerPulsar** [comment]
Well, mostly my lack of expertise with Zig. I've written a bit of code with it but I'm just using it as C+ basically. I guess a good way to introduce someone to the codebase would be to show a brief example of how to add an "idiomatic" but simple widget. 

For example: before making this issue, I tried playing around with text fields so that I could pass a float, display it, edit it, then return the new value if valid once enter is pressed. I mostly got it working, but wasn't quite sure how to make it easy to use. I needed to manually setup some persistent buffer to store the value of the string as it's edited, and a persistent float to store the initial value (I think this could be removed though). This of course wouldn't scale well to multiple textfields. I took a look at the source code for sliders and textfields since I needed float manipulation from the former, and input handling from the latter, but couldn't figure out how to make it easy to use, i.e. 
```
// Could also just the previous valid value of `my_float` in case an invalid input was given and forego the optional
const new_float: ?f32 = dvui.numField(@src(), my_float, ...); 
```
As I understand it, ImGui does this by having some sort of persistent buffer that maps the widget's id to its data. So something like this would touch almost all basic parts of the library: handling inputs, memory management, etc..

**Comment by david-vanderson** [comment]
That is fantastic!  You got way further than I expected.  Sounds like we need a doc that touches on all the various parts that are needed to make a new widget, with a motivating example like you said.  I think you are looking for dataSet/dataGet which will store arbitrary data associated with a widget id.

Can you post whatever code you have (doesn't have to run)?  Maybe this can be the motivating example, and being able to see what you were trying would be a great help.

**Comment by david-vanderson** [comment]
https://github.com/david-vanderson/dvui/blob/master/INSIDE.md

I started writing this, but looking back over it so far, I'm pretty sure it needs to start with an example or 2.  I'm going to try some heavily commented code listing.

**Comment by david-vanderson** [comment]
I added the labelClick() example to INSIDE.md - Is that getting closer to what would be helpful?

**Comment by david-vanderson** [comment]
I've added a start at this.  See `sliderEntry()` and the example in the Basic Widgets section of the demo window.  Needs some polish, but how does that look for a start?

Also please look at the sliderEntry code.  Is it somewhat understandable?

**Comment by KnockerPulsar** [comment]
Apologies for not replying sooner, I was busy away from my computer all day yesterday.

> Can you post whatever code you have (doesn't have to run)? Maybe this can be the motivating example, and being able to see what you were trying would be a great help.

<details>
<summary>Sure, here it is</summary>

```zig
fn floatTextEntry(buff: []u8) ?f32 {
    {
        var hbox = dvui.box(@src(), .horizontal, .{}) catch unreachable;
        defer hbox.deinit();

        // dvui.label(@src(), "Text Entry Singleline", .{}, .{ .gravity_y = 0.5 }) catch unreachable;
        var te = dvui.TextEntryWidget.init(@src(), .{ .text = buff }, .{});
        te.install() catch unreachable;

        var enter_pressed = false;
        const emo = te.eventMatchOptions();
        for (dvui.events()) |*e| {
            if (!dvui.eventMatch(e, emo))
                continue;

            if (e.evt == .key and e.evt.key.code == .enter and e.evt.key.action == .down) {
                e.handled = true;
                enter_pressed = true;
            }

            if (!e.handled) {
                te.processEvent(e, false);
            }

            if (enter_pressed) {
                return (std.fmt.parseFloat(f32, x_buff[0..te.len]) catch null);
            }
        }

        te.draw() catch unreachable;
        te.deinit();

        return null;
    }

    return null;
}

var x_buff = std.mem.zeroes([30]u8);
pub fn renderDvui(v: *Float3) bool {
    const x_new = floatTextEntry(&x_buff) orelse return false;
    v.*[0] = x_new;
    return true;
}
```
</details>

> https://github.com/david-vanderson/dvui/blob/master/INSIDE.md
>
> I started writing this, but looking back over it so far, I'm pretty sure it needs to start with an example or 2. I'm going to try some heavily commented code listing.

> I added the labelClick() example to INSIDE.md - Is that getting closer to what would be helpful?

> I've added a start at this. See sliderEntry() and the example in the Basic Widgets section of the demo window. Needs some polish, but how does that look for a start?
>
> Also please look at the sliderEntry code. Is it somewhat understandable?

I'll try going through them today and giving back feedback, stay tuned!

**Comment by KnockerPulsar** [comment]
INSIDE.md:
- The block with `me.action == .position`, as I understand it, should be "If the frame ends with the mouse inside the rectangle encompassing the widget, then this event is sent."
- Perhaps the mouse event code could be moved to a separate function so it's easier to get an overview of the whole function? I'm not sure about this, just going off my gut feeling. I understand that you may be aiming to keep the code for a widget in just one function to make it easy to understand.
- Minor thing, the last bullet point under `init` has a normal text "init()", not sure if this is intentional or not.
- Under `install()`, "maybe set the clip rect" can probably be elaborated further upon. I think you mean something like "glScissors" right? If so, perhaps can be reworded to "Maybe set drawing boundaries to prevent visual artifacts or unintentionally drawing over other widgets."
- The part talking about `FloatingWindowWidget` handling some events before/after their children. I think in the case of the floating window, resizing is done before so that children can update their sizes. If my understanding is correct, perhaps you can mention this fact?
- While reading your interface article, I found out that I already came across [another article of yours](https://zig.news/david_vanderson/switching-strings-with-a-var-4hl6) completely accidentally before :D

Overall, the document cleared up a lot of stuff that I didn't understand. It's getting quite late here to read any more code, so I'll check out `sliderEntry()` tomorrow.

**Comment by KnockerPulsar** [comment]
Checked out `sliderEntry()`, it has some bugs:
- When you enter the text field mode, clicking outside of the widget doesn't reset it to the slider mode
- If  you set a value outside the default range (0-1), the slider handle will be drawn outside the box
- Whenever an invalid float value is entererd ("asdad" for example), the slider value is set to 0. I can't quite remember how ImGui does this but I think it should just stay the same if possible

Some suggestions:
- Perhaps allow eithe specifying a min and max or neither through an optional `Range` struct. 
  - If a range is given, can then figure out the value by lerping based on the mouse position
  - If no range is given, can use a rate (0.05 for example) for each pixel of movement, the handle should probably not be drawn too.
  
The code seems readable overall, I got the main idea behind the widget can can probably work on it a bit to understand the remaining nuances. I'll try fiddling with the bug fixes and my suggestions later on today if you haven't already addressed them by then.

**Comment by david-vanderson** [comment]
Thanks so much for the docs feedback and the testing!

I'll give answers here as well as update the docs, and then followup with the bugfixes after.

> The block with me.action == .position, as I understand it, should be "If the frame ends with the mouse inside the rectangle encompassing the widget, then this event is sent."

Yes, although to be super precise that event is always in the event array (at the end).  Each widget calls eventMatch with it's screen rectangle which returns true if the event is inside that rectangle.  Probably we mean the same thing, but instead of the library sending events to widgets, the widgets can directly inspect the event array.  I'll try and emphasize that in the docs.

> Perhaps the mouse event code could be moved to a separate function so it's easier to get an overview of the whole function? I'm not sure about this, just going off my gut feeling. I understand that you may be aiming to keep the code for a widget in just one function to make it easy to understand.

Good point - let's try with a higher-level example at the start.  Maybe the code for `button()` is better?

> Minor thing, the last bullet point under init has a normal text "init()", not sure if this is intentional or not.

It was wrong.  Thanks!

>  Under install(), "maybe set the clip rect" can probably be elaborated further upon. I think you mean something like "glScissors" right? If so, perhaps can be reworded to "Maybe set drawing boundaries to prevent visual artifacts or unintentionally drawing over other widgets."

Yes - thanks!

> The part talking about FloatingWindowWidget handling some events before/after their children. I think in the case of the floating window, resizing is done before so that children can update their sizes. If my understanding is correct, perhaps you can mention this fact?

Sorry I messed that part up.  It was not supposed to be about sizing.  Its about which widget processes a mouse event when multiple widgets have overlapping screen rectangles.  For example a click in the lower-right corner of a floating window.  By processing this event before children, even if there is a button in the lower-right corner of the window, the click is processed by the window for drag-resizing.  I feel like I'm not doing a great job of explaining this.  Try reading the "Event Handling" section I wrote in [INSIDE](https://github.com/david-vanderson/dvui/blob/master/INSIDE.md) - does that help?

> While reading your interface article, I found out that I already came across [another article of yours](https://zig.news/david_vanderson/switching-strings-with-a-var-4hl6) completely accidentally before :D

Cool - thanks!

**Comment by david-vanderson** [comment]
Oh I wanted to say thank you for asking for this kind of combined widget.  It helped fix a design issue concerning who calls `eventMatch()`.  Now we call `matchEvent()` directly on the widget (which calls `eventMatch()` internally, but might call it multiple times for child widgets).  That makes nested compound widgets work, like how `sliderEntry` internally has a `textEntry` which internally has a `textLayout`.

Thanks!

**Comment by KnockerPulsar** [comment]
Alright, I checked out the changes in [INSIDE](https://github.com/david-vanderson/dvui/blob/master/INSIDE.md). I think all my points were well addressed. I also think it should perhaps link to `sliderEntry()` or any other persistent widget as an intermediate example. Just a link should be fine in my opinion. 

As for the accidental bug discovery, I'm glad that it was discovered, hopefully I can help you discover more bugs soon :)

Sorry for not posting any updates regarding the bugs, got a bit busy and haven't had a chance at trying my hand at them. I also saw that you already addressed one or two of them in 0dfc88ca71587ddae4029743a8bd7e639bfa9fee, thanks a lot! I'll poke around first thing tomorrow and post any updates I have.

Suggestion: Perhaps an extra "vector" version of `sliderEntry()` could be provided? It would just be a convenience wrapper for 2, 3, or 4 component vectors. Something like `sliderVector(@src(), f32, 3, component_format, &vec, opts)` for a 3 component f32 vector/array (zig seems to allow conversion between the two), where `component_format` would define the formatting for all elements. I was aiming to work on something like this for my own project and PR it back here, so feel free to leave this to me.

**Comment by david-vanderson** [comment]
Excellent thanks!  Good idea on the linking to further examples - I'll figure that out.

Thanks very much for the bug hunting - I've hopefully addressed most of them.  The example got checkboxes for toggling the min/max so you can test what happens without one or both.  What do you think of the exponential ramp?

I think the remaining issues on my list are hover indication, optional interval (so when dragging the values are snapped to multiples of the interval), and keyboard left/right keys.

A vector version sounds great!  I'll leave it to you but don't hesitate to ask if needed.

**Comment by KnockerPulsar** [comment]
Hey! Got the vector version kinda figured out. Still have some stuff to improve (testing with integers for example), but I already spent a couple of hours fighting the compiler to use my local changes instead of pulling the remote code and hacking together the new widget. So I'll continue work later.

Regarding the exponential ramp, I think it may be a bit too much? I think a default linear one should be fine-ish. Perhaps it can be configured to allow for custom + inbuilt functions?

**Comment by david-vanderson** [comment]
Looks good so far!

Yes zig's package manager still has some sharp corners as it's being developed, especially at version 0.11.x.  Maybe my podcast app's build.zig can help - when I'm co-developing dvui and the podcast, I turn `local_dev` to true:
https://github.com/david-vanderson/podcast/blob/main/build.zig

I've tamped down on the exponential ramp, how's it now?  You can play around with the new constants at the top of sliderEntry and let me know what those values should be.

I think sliderEntry has gotten to a pretty good spot so far feature wise.  I'm not sure about making the ramp function be customizable, or making it generic over floats/ints.  Maybe we wait and see and get some experience with the current version?

**Comment by KnockerPulsar** [comment]
Just went through the code and tried adding support for signed integers (i32), I don't think it's worth it really at this point since the code becomes a lot less readable. Here's the diff for future reference

<details>
<summary>diff</summary>

```diff
@@ -7931,17 +7931,50 @@ pub var slider_entry_defaults: Options = .{
     // min size calulated from font
 };
 
-pub const SliderEntryInitOptions = struct {
-    value: *f32,
-    min: ?f32 = null,
-    max: ?f32 = null,
-    interval: ?f32 = null,
-};
+pub fn SliderEntryInitOptions(comptime value_type: type) type {
+    switch (@typeInfo(value_type)) {
+        .Int, .Float => {
+            return struct {
+                value: *value_type,
+                min: ?value_type = null,
+                max: ?value_type = null,
+                interval: ?value_type = null,
+            };
+        },
+        else => {
+            @compileError("Only floats and integers are supported!");
+        },
+    }
+}
+
+fn numCast(comptime target_type: type, num: anytype) target_type {
+    switch (@typeInfo(@TypeOf(num))) {
+        .Int => switch (@typeInfo(target_type)) {
+            .Int => return @intCast(num),
+            .Float => return @floatFromInt(num),
+            else => @compileError("Cannot cast integers to the requested type"),
+        },
+        .Float => switch (@typeInfo(target_type)) {
+            .Float => return @floatCast(num),
+            .Int => return @intFromFloat(num),
+            else => @compileError("Cannot cast floats to the requested type"),
+        },
+        else => @compileError("Can can only cast integer and floats"),
+    }
+}
+
+fn numToFloat(num: anytype) f32 {
+    switch (@typeInfo(@TypeOf(num))) {
+        .Int => return @floatFromInt(num),
+        .Float => return @floatCast(num),
+        else => @compileError("Unsupported type"),
+    }
+}
 
 /// Combines a slider and a text entry box on key press.  Displays value on top of slider.
 ///
 /// Returns true if percent was changed.
-pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const u8, init_opts: SliderEntryInitOptions, opts: Options) !bool {
+pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const u8, comptime value_type: type, init_opts: SliderEntryInitOptions(value_type), opts: Options) !bool {
 
     // This widget swaps between either a slider with a label or a text entry.
     // The tricky part of this is maintaining focus.  Strategy is a containing
@@ -7974,8 +8007,8 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
 
     // must call dataGet/dataSet on these every frame to prevent them from
     // getting purged
-    _ = dataGet(null, b.data().id, "_start_x", f32);
-    _ = dataGet(null, b.data().id, "_start_v", f32);
+    _ = dataGet(null, b.data().id, "_start_x", value_type);
+    _ = dataGet(null, b.data().id, "_start_v", value_type);
 
     if (text_mode) {
         var te_buf = dataGetSlice(null, b.data().id, "_buf", []u8) orelse blk: {
@@ -8046,7 +8079,7 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
             refresh(null, @src(), b.data().id);
 
             if (new_val) |nv| {
-                init_opts.value.* = nv;
+                init_opts.value.* = @as(value_type, @bitCast(nv));
                 ret = true;
             }
         }
@@ -8084,7 +8117,7 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
                         } else {
                             captureMouse(b.data().id);
                             p = me.p;
-                            dataSet(null, b.data().id, "_start_x", me.p.x);
+                            dataSet(null, b.data().id, "_start_x", numCast(value_type, me.p.x));
                             dataSet(null, b.data().id, "_start_v", init_opts.value.*);
                         }
                     } else if (me.action == .release and me.button.pointer()) {
@@ -8108,10 +8141,14 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
                                 if (pp.x > max_x) {
                                     init_opts.value.* = init_opts.max.?;
                                 } else {
-                                    const px_lerp = @max(0, @min(1, (pp.x - min_x) / (max_x - min_x)));
-                                    init_opts.value.* = init_opts.min.? + px_lerp * (init_opts.max.? - init_opts.min.?);
+                                    const px_lerp: f32 = @max(0, @min(1, (pp.x - min_x) / (max_x - min_x)));
+                                    const min = numCast(f32, init_opts.min.?);
+                                    const max = numCast(f32, init_opts.max.?);
+                                    const lerp_result = min + px_lerp * max - min;
+                                    init_opts.value.* = numCast(value_type, lerp_result);
+
                                     if (init_opts.interval) |ival| {
-                                        init_opts.value.* = init_opts.min.? + ival * @round((init_opts.value.* - init_opts.min.?) / ival);
+                                        init_opts.value.* = numCast(value_type, init_opts.min.?) + ival * numCast(value_type, @round(numCast(f32, (init_opts.value.* - init_opts.min.?)) / numCast(f32, ival)));
                                     }
                                 }
                             } else if (init_opts.min != null) {
@@ -8119,12 +8156,12 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
                                 if (pp.x < min_x) {
                                     init_opts.value.* = init_opts.min.?;
                                 } else {
-                                    const base = if (init_opts.min.? == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(init_opts.min.?)))) * 0.01;
+                                    const base = if (init_opts.min.? == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(numCast(f32, init_opts.min.?))))) * 0.01;
                                     const how_far = @max(0, (pp.x - min_x)) / px_scale;
-                                    const how_much = (@exp(how_far * 0.03) - 1) * base;
-                                    init_opts.value.* = init_opts.min.? + how_much;
+                                    const how_much = numCast(f32, (@exp(how_far * 0.03) - 1) * base);
+                                    init_opts.value.* = numCast(value_type, numCast(f32, init_opts.min.?) + how_much);
                                     if (init_opts.interval) |ival| {
-                                        init_opts.value.* = init_opts.min.? + ival * @round((init_opts.value.* - init_opts.min.?) / ival);
+                                        init_opts.value.* = numCast(value_type, numCast(f32, init_opts.min.?) + numCast(f32, ival) * @round(numCast(f32, (init_opts.value.* - init_opts.min.?)) / numCast(f32, ival)));
                                     }
                                 }
                             } else if (init_opts.max != null) {
@@ -8132,24 +8169,24 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
                                 if (pp.x > max_x) {
                                     init_opts.value.* = init_opts.max.?;
                                 } else {
-                                    const base = if (init_opts.max.? == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(init_opts.max.?)))) * 0.01;
+                                    const base = if (init_opts.max.? == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(numCast(f32, init_opts.max.?))))) * 0.01;
                                     const how_far = @max(0, (max_x - pp.x)) / px_scale;
-                                    const how_much = (@exp(how_far * 0.03) - 1) * base;
-                                    init_opts.value.* = init_opts.max.? - how_much;
+                                    const how_much = numCast(f32, (@exp(how_far * 0.03) - 1) * base);
+                                    init_opts.value.* = numCast(value_type, numCast(f32, init_opts.max.?) - how_much);
                                     if (init_opts.interval) |ival| {
-                                        init_opts.value.* = init_opts.max.? - ival * @round((init_opts.max.? - init_opts.value.*) / ival);
+                                        init_opts.value.* = numCast(value_type, numCast(f32, init_opts.max.?) - numCast(f32, ival) * @round(numCast(f32, (init_opts.max.? - init_opts.value.*)) / numCast(f32, ival)));
                                     }
                                 }
                             } else {
                                 // neither min nor max, go exponentially away from starting value
-                                if (dataGet(null, b.data().id, "_start_x", f32)) |start_x| {
-                                    if (dataGet(null, b.data().id, "_start_v", f32)) |start_v| {
-                                        const base = if (start_v == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(start_v)))) * 0.01;
-                                        const how_far = (pp.x - start_x) / px_scale;
-                                        const how_much = (@exp(@fabs(how_far) * 0.03) - 1) * base;
-                                        init_opts.value.* = if (how_far < 0) start_v - how_much else start_v + how_much;
+                                if (dataGet(null, b.data().id, "_start_x", value_type)) |start_x| {
+                                    if (dataGet(null, b.data().id, "_start_v", value_type)) |start_v| {
+                                        const base = if (start_v == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(numCast(f32, start_v))))) * 0.01;
+                                        const how_far = (pp.x - numCast(f32, start_x)) / numCast(f32, px_scale);
+                                        const how_much = numCast(f32, (@exp(@fabs(how_far) * 0.03) - 1) * base);
+                                        init_opts.value.* = numCast(value_type, if (how_far < 0) numCast(f32, start_v) - how_much else numCast(f32, start_v) + how_much);
                                         if (init_opts.interval) |ival| {
-                                            init_opts.value.* = start_v + ival * @round((init_opts.value.* - start_v) / ival);
+                                            init_opts.value.* = numCast(value_type, numCast(f32, start_v) + numCast(f32, ival) * @round(numCast(f32, (numCast(f32, init_opts.value.*) - numCast(f32, start_v))) / numCast(f32, ival)));
                                         }
                                     }
                                 }
@@ -8179,9 +8216,9 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
                             if (init_opts.interval) |ival| {
                                 init_opts.value.* = init_opts.value.* + (if (how_far < 0) -ival else ival);
                             } else {
-                                const base = if (init_opts.value.* == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(init_opts.value.*)))) * 0.01;
-                                const how_much = (@exp(@fabs(how_far) * 0.03) - 1) * base;
-                                init_opts.value.* = if (how_far < 0) init_opts.value.* - how_much else init_opts.value.* + how_much;
+                                const base = if (init_opts.value.* == 0) 0.01 else @exp(math.ln10 * @floor(@log10(@fabs(numCast(f32, init_opts.value.*))))) * 0.01;
+                                const how_much = numCast(f32, (@exp(@fabs(how_far) * 0.03) - 1) * base);
+                                init_opts.value.* = numCast(value_type, if (how_far < 0) numCast(f32, init_opts.value.*) - how_much else numCast(f32, init_opts.value.*) + how_much);
                             }
 
                             if (init_opts.min) |min| {
@@ -8206,7 +8243,7 @@ pub fn sliderEntry(src: std.builtin.SourceLocation, comptime label_fmt: ?[]const
 
         // only draw handle if we have a min and max
         if (init_opts.min != null and init_opts.max != null) {
-            const how_far = (init_opts.value.* - init_opts.min.?) / (init_opts.max.? - init_opts.min.?);
+            const how_far = numCast(f32, (init_opts.value.* - init_opts.min.?)) / numCast(f32, (init_opts.max.? - init_opts.min.?));
             const knobRect = Rect{ .x = (br.w - knobsize) * math.clamp(how_far, 0, 1), .w = knobsize, .h = knobsize };
             const knobrs = b.widget().screenRectScale(knobRect);
 
@@ -8247,7 +8284,13 @@ pub fn sliderVector(line: std.builtin.SourceLocation, comptime fmt: []const u8,
     var any_changed = false;
     inline for (0..num_components) |i| {
         // `catch false` because otherwise (`try`) would cause issues where the (i+1)th, (i+2)th, ... components would not get drawn properly while ith is modified.
-        const component_changed = dvui.sliderEntry(line, fmt, .{ .value = &data_arr[i] }, opts.override(.{ .id_extra = i })) catch false;
+        const component_changed = dvui.sliderEntry(
+            line,
+            fmt,
+            component_type,
+            SliderEntryInitOptions(component_type){ .value = &data_arr[i] },
+            opts.override(.{ .id_extra = i }),
+        ) catch false;
         any_changed = any_changed or component_changed;
     }
```
</details>

I'll check out your recent changes and provide feedback soon!

**Comment by KnockerPulsar** [comment]
Sorry for taking so long, I checked commits for the last few days and can say I'm very satisfied with the solution we've got up until now. Hence, I'll close this issue. Feel free to re-open if you want to discuss further. Thanks for the great work!

**Comment by david-vanderson** [comment]
Excellent!  Thank you for the suggestion and all the feedback on both the code and the docs!
