### ISSUE TITLE
weird interaction in demo window

### ISSUE THREAD

**Issue by iacore** [david-vanderson/dvui#50]
1. swish swash i feel dizzy
2. it doesn't remember the position (being on right panel) when the window is resized and back

https://github.com/david-vanderson/dvui/assets/74560659/e9fbca65-15f5-419a-8236-84f172c377c7

**Comment by david-vanderson** [comment]
Good points - I'll work on it.

**Comment by david-vanderson** [comment]
I think I've addressed both.  How is it now?

**Comment by iacore** [comment]
confirm fixed!

**Comment by david-vanderson** [comment]
Thanks!
