### ISSUE TITLE
id_extra being integer is unsound

### ISSUE THREAD

**Issue by iacore** [david-vanderson/dvui#55]
`.id_extra` should be at least a list of integers like `.{0, 1, 2}`
for convenience's sake, the slice should be comptime

it can also be (hash of the parent `src` + constant), but that's lower than hashing integers

## Explanation

The title of this issue might as well be "Cardinality: Trees Hate Me".

You can't put integer sets into integer sets into integer sets into .... without global state

![graphic](https://github.com/david-vanderson/dvui/assets/74560659/789c25a9-81b1-482f-81b2-d7a72fa8f475)

There are two ways of solving this problem.

- global incremental counter (ugly)
- hashing (need randomness and large enough space (number of bits used))

**Comment by iacore** [comment]
One cool idea I thought of that also solves #53:

```
fn widget_a(ctx: dvui.HierarchicalContext, ...) !void {
    const layout_opts = dvui.Options{ .expand = .horizontal };
    try dvui.label(ctx.child(@src(), layout_opts), label, .{}));
    //                       ^^^^^^ this is needed since `ctx` is immutable
}
```

**Comment by david-vanderson** [comment]
I'm sorry I don't understand the problem, I must be missing something obvious.  Right now we use hashing (parent's id plus @src plus id_extra).  Is there some pseudo code you can write to show me how that fails?

Having the @src is useful separately so the debug window can tell you where to look in the source for the widget you are pointing at.

**Comment by iacore** [comment]
Is there a function that allows you to pass `@src()` as `.id_extra`? For example, to hash it.

> I'm sorry I don't understand the problem, I must be missing something obvious.

It's mathematically unsound. You are trying to put a set with cardinality $\aleph_1$ into a set with cardinality $\aleph_0$, which is impossible.

> Is there some pseudo code you can write to show me how that fails?

Let's say you have deeply nested components, and you can't change `main`.

```
fn main() {
  component_a(@src());
}
fn component_a(src) {
  component_b(...); // what do you put here to replace "..."?
  component_b(...);
  component_b(...);
}
fn component_b(src) {
  component_c(...);
  component_c(...);
  component_c(...);
}
fn component_c(src) {
  dvui.label(...);
}
```

first we try passing an extra integer in (current `.id_extra` solution)

```
fn component_a(src) {
  component_b(src, 0);
  component_b(src, 1);
  component_b(src, 2);
}
fn component_b(src, id0) {
  component_c(src, id0, 0);
  component_c(src, id0, 1);
  component_c(src, id0, 2);
}
fn component_c(src, id0, id1) {
  dvui.label(src, .{.id_extra=what do i put here});
}
```

That's why it's a problem.

**Comment by david-vanderson** [comment]
Okay I think I see where we are differing.  Let me take the example you gave in the gravity issue:
```zig
fn input_field(src: std.builtin.SourceLocation, comptime label: []const u8, text: []u8) !void {
    const opts_vert_align: dvui.Options = .{ .gravity_y = 0.5 };

    var box = try dvui.box(src, .horizontal, .{ .expand = .horizontal, .id_extra = 0 });
    defer box.deinit();
    try dvui.label(src, label, .{}, opts_vert_align.override(.{ .id_extra = 1 }));
    var txt_domain = try dvui.textEntry(src, .{ .text = text }, opts_vert_align.override(.{ .expand = .horizontal, .id_extra = 2 }));
    txt_domain.deinit();
}
```
I think you have the right intuition for passing `src` into `input_field`, but everything inside `box` will inherit its id as part of the hash.  So you can do this:

```zig
fn input_field(src: std.builtin.SourceLocation, comptime label: []const u8, text: []u8) !void {
    const opts_vert_align: dvui.Options = .{ .gravity_y = 0.5 };

    var box = try dvui.box(src, .horizontal, .{ .expand = .horizontal });
    defer box.deinit();
    try dvui.label(@src(), label, .{}, opts_vert_align);
    var txt_domain = try dvui.textEntry(@src(), .{ .text = text }, opts_vert_align.override(.{ .expand = .horizontal }));
    txt_domain.deinit();
}
```

And then if you were going to have a lot of `input_field` in a loop, you probably want it to accept an Options parameter.  Does this help?

**Comment by iacore** [comment]
> everything inside box will inherit its id as part of the hash

I was, in fact, not aware of this.

Is it possible to design the API of DVUI in a way that someone can discover the correct usage without reading the source code of DVUI?

Here's what I tried, in this order:

- use 3 `@src()`. outcome: duplicate id
- use 3 `src`. outcome: duplicate id
- use 3 `src` with `id_extra`. outcome: works

So, I don't think I would have found the correct usage had you not mentioned it to me.

**Comment by david-vanderson** [comment]
I'm glad we figured out the misunderstanding, but I'm sorry the design/docs/examples failed you here.

I've rewritten the implementation docs about widget ids here.  Does it make sense?
https://github.com/david-vanderson/dvui/blob/master/readme-implementation.md#widget-ids

And now the error message you get with duplicate ids has that link in it.  Do you think this will help?

**Comment by iacore** [comment]
> I've rewritten the implementation docs about widget ids here. Does it make sense? https://github.com/david-vanderson/dvui/blob/master/readme-implementation.md#widget-ids
> 
> And now the error message you get with duplicate ids has that link in it. Do you think this will help?

Almost there! We still need a one-sentence explanation of what a "parent" is (without relying on knowledge of implementation details).

**Comment by iacore** [comment]
Better yet, is there a way to create a virtual parent (a thing that does nothing but is in the parent chain)? This will also make debugging easier, since custom widgets (like `input_field`) will now appear as any other widgets too.

```
fn input_field(src: std.builtin.SourceLocation, comptime label: []const u8, text: []u8) !void {
    const current_widget = dvui.initVirtualWidget(src);
    defer current_widget.deinit();

    const opts_vert_align: dvui.Options = .{ .gravity_y = 0.5 };

    var box = try dvui.box(@src() .horizontal, .{ .expand = .horizontal });
    defer box.deinit();
    try dvui.label(@src(), label, .{}, opts_vert_align);
    var txt_domain = try dvui.textEntry(@src(), .{ .text = text }, opts_vert_align.override(.{ .expand = .horizontal }));
    txt_domain.deinit();
}
```

**Comment by david-vanderson** [comment]
I might be misunderstanding, but there is no widget that doesn't affect layout.  The parent's main job is to layout the children.  When you write:
```
dvui.label(@src(), "a");
dvui.label(@src(), "b");
```
The position of those 2 labels is entirely up to the current parent.

Because of this, compound widgets always start with a single containing widget that handles layout for the rest.  There might be a situation where you want a function that doesn't do that, and just adds a series of widgets (leaving it up to the caller to decide what parent to use for layout), but I haven't run into that yet.  Have you?

**Comment by iacore** [comment]
> There might be a situation where you want a function that doesn't do that, and just adds a series of widgets (leaving it up to the caller to decide what parent to use for layout), but I haven't run into that yet. Have you?

Yes I have, when using DVUI.

I come from the web design world and brought that habit with me.

Here's [an example in Solid](https://playground.solidjs.com/anonymous/be23a224-94a6-40d8-be22-97980288d6d4). Note that there's only one list (`<ul>`).

**Comment by david-vanderson** [comment]
Okay thank you.  I think I finally have gotten it.  To restate the problem, you have a parent container (say `BoxWidget`), and then you are going to call a bunch of functions that all add children to that parent.  Some of those functions might be called multiple times, so they will be adding a child with the same @src to the same parent, resulting in duplicate ids.  And it's annoying (and maybe quite hard) to thread an extra `id_extra` param through all the functions and keep it straight.

So you are looking for a way inside one of these functions to wrap all the widgets in a way that will change the IDs but still leave them logically as children of the original parent (at least for layout purposes).

Have I got it now?

If so, one possibility would be a virtual parent widget that forwarded all parent calls to the next parent, but adjust the IDs.  It would use a global counter that started at 0 each frame and incremented each time a new virtual parent widget was created.

The downside is that any change in the list of children (like the first one gets removed, or one is inserted in the middle) would give a frame where some widgets would be using IDs of different wigets from the previous frame.  This could in theory produce all kinds of problems, especially if widgets are using dataSet/dataGet.

I wonder if we can get a stacktrace from zig and hash that?  Any other ideas?

**Comment by iacore** [comment]
> Have I got it now?

yes, exactly!

> If so, one possibility would be a virtual parent widget that forwarded all parent calls to the next parent, but adjust the IDs. It would use a global counter that started at 0 each frame and incremented each time a new virtual parent widget was created.
>
> The downside is that any change in the list of children (like the first one gets removed, or one is inserted in the middle) would give a frame where some widgets would be using IDs of different wigets from the previous frame. This could in theory produce all kinds of problems, especially if widgets are using dataSet/dataGet.

global counter is bad idea. use only hash.

> I wonder if we can get a stacktrace from zig and hash that? Any other ideas?

That was my idea. The public API better not acquire the user to do that though.

This is my public API design:

```
  const p = dvui.VirtualParent.init(src); // hash happens within
  defer p.deinit();
```

**Comment by david-vanderson** [comment]
Oh good!  I've added a virtual parent widget, but it doesn't know how to do the hash yet.  So currently it's relying on the user passing `.id_extra`.  But at least this validates the part where we can have a parent that doesn't affect layout.  Check it out (I put an example at the beginning of the Examples Layout section).

Still trying to figure out what to hash.

**Comment by iacore** [comment]
> Still trying to figure out what to hash.

you don't need to do hash anything!

I have pushed the fix. take a look.

**Comment by david-vanderson** [comment]
Excellent!  Thanks so much for sticking with it!
