### ISSUE TITLE
use proper colorspace for color operations

### ISSUE THREAD

**Issue by iacore** [david-vanderson/dvui#56]
cannot lighten black

`0 * (1 + y) == 0`

https://github.com/david-vanderson/dvui/blob/811e8d93f9f55c0a16d18d45e61a2db646198b52/src/Color.zig#L28-L35

**Comment by david-vanderson** [comment]
Yep you are right.  Do you know what we should be doing here?  My guess is that we need some colorspace conversion functions (cielab?) so that lighten/darken use that.  Do you know which we should use?

**Comment by iacore** [comment]
CIELUV.

https://www.hsluv.org/
https://www.kuon.ch/post/2020-03-08-hsluv/
https://gist.github.com/denis-bz/ec601823dc52666812a3e27b88772a84

I vaguely remember porting the conversion code between sRGB and HSLuv from d3.js (Javascript) to Rust or C, but I cannot find the code.

What rendering API do we even use? We need control over colorspace.

**Comment by david-vanderson** [comment]
Excellent - thanks for that.  As for rendering API, for the SDL backend we use `SDL_RenderGeometryRaw` and I haven't dug into it to figure out what's going on with colorspaces.  For the mach backend (which I will make work again at some point), it uses webgpu with some shaders I wrote, but again I haven't thought about colorspaces yet.

I think a great step would be to have conversion code so that we have nicer darken/lighten functions.  Thank you!

**Comment by iacore** [comment]
I have ported [ok_color.h](https://github.com/godotengine/godot/blob/master/thirdparty/misc/ok_color.h) to C. -> branch `ok_color`
This branch can't build because the color space conversion code is down at compile time. Can't call into C code at compile time.

I have also attempted to translate it to Zig, but it's difficult so I gave up. -> branch `ok_color`
I think eventually `zig translate-c` will get good enough that this becomes automatic.

**Comment by david-vanderson** [comment]
Thanks very much.  I really appreciate you taking the time to dig into this.  I will pick up where you left off soon and see if I can make progress.

**Comment by iacore** [comment]
One idea is to generate the palette at the start of run-time instead of at compile-time. You can do this in `dvui.init()`.

**Comment by iacore** [comment]
I can't. Either `zig c-translate` produced invalid code, or the original algorithm is buggy.

**Comment by david-vanderson** [comment]
I was finally able to hand-convert hsluv.c to zig.  The adwaita theme code is specifying colors using it, and the demo window (under styling) has HSLuv sliders.

This is just a start and I'm unsure what the path forward is, but being able to convert to HSLuv and back (HPLuv is also implemented) is a big improvement from where we were.

Thanks for the help here!

**Comment by david-vanderson** [comment]
That's right.  It looked the easiest to port and had test data.

**Comment by iacore** [comment]
Is this issue done now?

**Comment by david-vanderson** [comment]
I think so.  Likely there will be follow-on stuff regarding more colorspace stuff, but this is a good start.  Thanks!
