### ISSUE TITLE
cursor shapes on Linux are incorrect

### ISSUE THREAD

**Issue by iacore** [david-vanderson/dvui#58]

**Comment by david-vanderson** [comment]
Sorry I missed this - can you provide any details about which distribution you are using, and which cursor shapes are wrong?

**Comment by iacore** [comment]
Distribution doesn't matter, probably. The X11/SDL cursor shapes should be the same across all.

So far, only the resize seems to be "wrong" (unconventional).

https://github.com/david-vanderson/dvui/assets/74560659/3d40369a-bd1b-43f7-a854-3ebb163d9c3b

**Comment by iacore** [comment]
SDL's built-in cursors are not working as intended...

this is `*_SIZENWSE`

![image](https://github.com/david-vanderson/dvui/assets/74560659/3b68a914-a90f-46f6-953c-bd2a79b3f21d)

**Comment by david-vanderson** [comment]
Thanks!  I've also noticed that on some platforms I don't get the cursors I expect with SDL.  I'm hopeful that SDL3 will help here.
