### ISSUE TITLE
setWindowIcon

### ISSUE THREAD

**Issue by r4gus** [david-vanderson/dvui#59]
SDL has a [`SDL_SetWindowIcon`](https://wiki.libsdl.org/SDL2/SDL_SetWindowIcon) function that could be used with [`IMG_Load`](https://wiki.libsdl.org/SDL2_image/IMG_Load) to load a image (e.g. png) as icon.

**Comment by david-vanderson** [comment]
Excellent idea!  I've added it to the SDL backend and to the standalone-sdl.zig example.  How does it look?

**Comment by r4gus** [comment]
Damn you're quick. Looks awesome!

**Comment by david-vanderson** [comment]
Haha we just got incredibly lucky in timing.  Thanks!

**Comment by iacore** [comment]
I have cleaned up the code.

**Comment by david-vanderson** [comment]
That looks good, but can you (in addition) add the icon back to the SDLBackend.initOptions struct and have init call setIconFromFileContent if it is passed?  That will cover the common case of setting the icon at the beginning and never changing it.

Thanks!

**Comment by iacore** [comment]
> That looks good, but can you (in addition) add the icon back to the SDLBackend.initOptions struct and have init call setIconFromFileContent if it is passed? That will cover the common case of setting the icon at the beginning and never changing it.

Is this functionality needed? [See here](https://github.com/david-vanderson/dvui/blob/dc3faab53a2f431a83ab631321ba3abfb5e20fc9/standalone-sdl.zig#L26).

Logically speaking, the icon must be set after the window is created. the new API reflects that. It also forces the user to know that they can set the icon many times.

**Comment by david-vanderson** [comment]
While both ways work, I would like it included in the init options.  It's a natural place to look when wanting to add an icon.  I've made the change.  Thanks!
