### ISSUE TITLE
typo in the usage section of README.md

### ISSUE THREAD

**Issue by earthfail** [david-vanderson/dvui#76]
the code segment for `build.zig` should use the variable name dvui_dep and not dep_dvui, plus this matches the usage of [dvui demo](https://github.com/david-vanderson/dvui?tab=readme-ov-file#usage).

I would also like to suggest to provide a release or maybe suggest commit hash to start from  but I understand if it is not possible since it is cumbersome to manage (maybe add a note to use the same url and hash from in dvui-demo).

Thanks for the amazing library.

**Comment by david-vanderson** [comment]
Thanks for the careful reading and bug report!  It also revealed a bug in how dvui-demo was using dvui.

I've removed the copies of build.zig and build.zig.zon from the readme to leave just the link to dvui-demo.  That will help prevent this kind of bug.  Does that help?  Or do you think putting them back in (corrected) would be better?

I agree that some kind of release or tag would be nice, but I'm unsure how to do it.  I've tagged a "v0.1.0" and used that in dvui-demo.  Is that the kind of thing you are thinking of?

Thanks very much!

**Comment by earthfail** [comment]
Yes it helps. I think your approach it correct.
thank you and thanks for giving a tag. this way there is commit to test if my setup it correct

**Comment by david-vanderson** [comment]
Thanks!
