### ISSUE TITLE
Raylib Backend?

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#77]
Hello, dvui seems like a really cool project. It looks like this library is designed to support many different types of backends. I was wondering if a raylib backend would be a feasible option.

Many games use raylib so it would be nice to be able to integrate dvui into raylib projects for ui.

**Comment by david-vanderson** [comment]
Thank you!  I've read about raylib but haven't used it yet.  It certainly looks feasible.

Can you point me to a zig project that's using raylib so I can see an example of how to use it?

**Comment by VisenDev** [comment]
> Can you point me to a zig project that's using raylib so I can see an example of how to use it?

I've been developing a 2D adventure game in with raylib and zig for about a year now so that is one example. https://github.com/VisenDev/ziggity

Also, a few other notes
- Have you considered making a discord server for this project? I've found the servers for other zig projects like ziglua and ghostty to be very helpful for development. 
- Are you interested in theme contributions? I have been experimenting with a theme based on the Jungle raygui theme. I'd also like to work an a dracula based theme.

<img width="799" alt="Screenshot 2024-07-28 at 10 11 09 PM" src="https://github.com/user-attachments/assets/67ca192a-fc65-44bd-8fc4-d66cda668615">

**Comment by david-vanderson** [comment]
Thanks for the example!  Give me some time to dig into it a bit.

As for discord, you are right that it would be nice.  I'm very new to discord and don't quite understand how to start.  Is the right thing to create a "server"?  Or try to get a channel on some other server?

I'm very interested in theme submissions!  Please either point me to the theme code or make a PR.  I'd love to show off some themes in the examples.  Thanks!

**Comment by iacore** [comment]
> As for discord, you are right that it would be nice. I'm very new to discord and don't quite understand how to start. Is the right thing to create a "server"? Or try to get a channel on some other server?

Create a "server". Although I prefer Matrix / IRC more.

**Comment by david-vanderson** [comment]
Yes I would also prefer something like Matrix, but my understanding is that I'd have to setup and host a server for that.

I'm thinking we start with a free discord server, and see how useful it is.  We can always switch in the future.

**Comment by iacore** [comment]
> Yes I would also prefer something like Matrix, but my understanding is that I'd have to setup and host a server for that.

You can register and create a room on most servers. Anyone can create a room, not just the server owner.

**Comment by VisenDev** [comment]
Also, raylib is built off of opengl - so it would probably be possible to make an opengl backend that automatically also supports raylib.

**Comment by david-vanderson** [comment]
Good point, although I'm less sure how an opengl backend would work with stuff like getting the size of the window and accessing the clipboard.  There's surely a way to make it work, but let's focus on raylib for now.

**Comment by david-vanderson** [comment]
Split discussion space into separate issue https://github.com/david-vanderson/dvui/issues/85

**Comment by david-vanderson** [comment]
I think we've succeeded in the getting this off the ground.  Well done!

**Comment by VisenDev** [comment]
> I think we've succeeded in the getting this off the ground. Well done!

Yes, thanks for getting this moving so quickly! I only proposed this idea 2 weeks ago
