### ISSUE TITLE
Discussion space

### ISSUE THREAD

**Issue by david-vanderson** [david-vanderson/dvui#85]
A few people have asked for some kind of discussion space.  This issue is to gather feedback.

The options I know of are:
- discord
- matrix
- topic on ziggit.dev
- irc

I asked Loris Cro for advice.  He confirmed that most people are using one of those options, and advised us that the technical merits of the choice matter much less than people's willingness to use it.

Personally I don't have strong opinions about which option to go with, but will make a decision soon so we don't get stuck.  I also have no problems trying one for a while and then switching.  I'm sure @iacore will help keep me honest here!

Please comment if you have any kind of opinion about this.

**Comment by wwderw** [comment]
Given the most other projects that I follow are on Discord, just for that ease, I would go in that direction.

**Comment by VisenDev** [comment]
> Given the most other projects that I follow are on Discord, just for that ease, I would go in that direction.

I second this

**Comment by iacore** [comment]
discord frontend lags.

matrix and irc are both fine by me.

there's also Github Discussions.

**Comment by david-vanderson** [comment]
I should have said that I expect whatever discussion platform to be used for people discussing things and asking for help.  Any decisions or issues would still go through github.

So I don't want anyone to feel like they need to join the new platform.  Anyone is free to make a github issue or github discussion.  I also watch ziggit.dev and zig.news.

**Comment by VisenDev** [comment]
I really don't think it matters too much what exact platform you pick. The point is just to have some sort of chatroom where devs can communicate in a less formal manner than github issues.

**Comment by iacore** [comment]
Discord on my phone lags like hell, so it does matter to me.

> The point is just to have some sort of chatroom where devs can communicate in a less formal manner than github issues.

there is no one here to pressure you to be formal :)

**Comment by wilsonk** [comment]
I am on Discord for most other projects, which makes it easier for me if that is the channel of communication on this...so that is my vote :)  Of course, that may not be relevant for others (especially if they dislike Discord)...just me two cents.

**Comment by dhrubrawat66** [comment]
discord.

**Comment by david-vanderson** [comment]
How about we try using the existing zig #gui-dev channel and see how that feels?
This should be an invite to there: https://discord.gg/SzgAVS8M

**Comment by iacore** [comment]
nice choice allowing other zig users to chime in.

**Comment by david-vanderson** [comment]
I've added a discord link to the readme.  We'll go with that for now.
