### ISSUE TITLE
Native file open dialogs

### ISSUE THREAD

**Issue by david-vanderson** [david-vanderson/dvui#93]
https://github.com/david-vanderson/dvui/discussions/23

Idea is to have dvui create a modal dialog and at the same time use a library to launch the platform's native file open dialog.  When the native dialog is closed, the dvui dialog would extract the information and make it available to the app.

**Comment by iacore** [comment]
On Linux, use the command `zenity`.

**Comment by iacore** [comment]
I found something nice: https://sourceforge.net/projects/tinyfiledialogs/

It's C, which also can be ported to Zig.

**Comment by david-vanderson** [comment]
That looks pretty good.  @VisenDev mentioned https://github.com/samhocevar/portable-file-dialogs which compares itself to tinyfiledialogs, so probably either one is a good candidate.

**Comment by david-vanderson** [comment]
I just found out SDL3 has support for this: https://wiki.libsdl.org/SDL3/CategoryDialog

**Comment by david-vanderson** [comment]
I've pushed support for this using tinyfiledialogs.  The functions currently block, but that could be fixed in the future.

The demo "Dialogs / Toasts" has examples.

This closes this issue, but please reopen or file bugs if you see problems.  Thanks!
