### ISSUE TITLE
Proposal: Remove Text Events

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#94]
At the moment we have both text events and key change events. Why these are treated differently is not entirely clear - as they both handle key press events.

My understanding of why this is the case is because SDL treats these differently, but I find it confusing as to why these are not the same thing in dvui internally.

In particular, backends like raylib have to send 2 events for every key press. One Key event and one Text event.

This proposal is to remove TextEvents and make all keyboard status updates be sent thru Key Events to prevent the ambiguity between these two.

**Comment by david-vanderson** [comment]
It is weird the first time you encounter it, but it is needed to handle paste events in some situations (like in the web backend), and to eventually handle IME (Input Method Editor) - https://en.wikipedia.org/wiki/Input_method

For many languages, there is no one-to-one mapping between key presses and text input, and they don't even need to happen at the same time.

Separately, there is the question of "keyboard keys" vs. characters generated.  For the key press events, the idea is that they correspond to a particular physical key that was pressed.  This is like games asking for keyboard bindings.  For text input events, it could be different depending on the keyboard layout being used.  So if the user presses shift-a, we should get separate key events for shift and a, and a single text input event 'A'.

It's possible that dvui is not doing the best thing in this regard, but that's the goal.  Does that help explain it?

**Comment by VisenDev** [comment]
> So if the user presses shift-a, we should get separate key events for shift and a, and a single text input event 'A'.
> 
> It's possible that dvui is not doing the best thing in this regard, but that's the goal. Does that help explain it?

Okay this general idea makes sense. However, what is happening (at least in the raylib backend) is we are getting a key press event for `shift` with modifier "none", a key press event for "a" with modifier "shift", and a text entry event "A". This feels unnecessarily complicated but perhaps I have a lack in understanding. 

The text entry event needing to be called in the backend is completely superfluous as it could be generated automatically from a key-press with modifier "shift". For a "ctrl"+"v" key press event - the paste text event is generated automatically. 

Maybe the text event only needs to exist internally to dvui and not as an event to be called by the backend? IE, the backend only sends key press events and those key press events can trigger text entry events if necessary.

Because its a little complex differentiating between a key press event that requires a text event and one that doesn't in the backend. It seems like this functionality might be better suited for the `addEventKey` function since which key presses trigger text events needs to be consistent between backends (I assume?)

For example, the key event "shift+a" is now sent as a key press event of "a" with modifier "shift". The `addEventKey` function recognizes that this needs to trigger a text input event.

**Comment by david-vanderson** [comment]
The main drawback of trying to do that is that dvui would then have to understand the user's keyboard layout, which from what I have read is something we don't want to get into.  Most OSes will handle that themselves.

If someone is using a normal keyboard but has it configured for "dvorak" layout, then seeing "f" with modifier "shift" should produce "U", and seeing "f" with no modifier should produce "u".  I'm not totally sure that dvui is handling the difference correctly, but we at least get the right text with different layouts currently (in SDL and web backends).

**Comment by VisenDev** [comment]
> but we at least get the right text with different layouts currently (in SDL and web backends).

Ah I don't know how raylib handles this, but it doesn't have separate key and text events. Working with the raylib event system may have distracted me from how other backends utilize text events.

**Comment by david-vanderson** [comment]
No problem - as long as the raylib backend is working for you, we can wait until that kind of usecase comes up to figure it out.
