### ISSUE TITLE
Proposal: Remove specific `win.addEventX` functions in favor of generic addEvent function

### ISSUE THREAD

**Issue by VisenDev** [david-vanderson/dvui#95]
In the SDL backend, the generic `SDL_Event` object is sent to the `SDLBackend.addEvent` function, which then breaks down the `SDL_Event` based on the event type and calls the specific `win.addEventX` type for that event type. 

Each of those `win.addEventX` functions then use this data to form a generic `dvui.Event` for processing. 

This intermediary step of registering the SDL_Event using different specific `win.addEventX` functions seems unnecessary. This proposal recommends eliminating this step in favor of directly parsing the `SDL_Event` into a `dvui.Event` and registering it.

I came across this when experimenting with the construction of a generic `RaylibEvent` type as discussed in https://github.com/david-vanderson/dvui/pull/92 . I realized the type I was creating basically already existed in `Event.zig` here

```zig
evt: union(enum) {
    // non-bubbleable
    mouse: Mouse,

    // bubbleable
    key: Key,
    text: []u8,
    close_popup: ClosePopup,
    scroll_drag: ScrollDrag,
    scroll_to: ScrollTo,
    scroll_propogate: ScrollPropogate,
},
```

I realized I could just parse all the raylib events into a `@TypeOf(dvui.Event.evt)` rather than creating my own bespoke type for Events. Doing this would also make all of the specific `win.addEventX` functions kind of unnecessary. 

Hence I realized the same strategy could also be used to for other backends

If this proposal is supported - it would probably also be best to considering slight refactors to `Event.zig`. Probably going from this

```zig
const Event = @This();

handled: bool = false,
focus_windowId: ?u32 = null,
focus_widgetId: ?u32 = null,
// num increments withing a frame, used in focusRemainingEvents
num: u16 = 0,
evt: union(enum) {
    // non-bubbleable
    mouse: Mouse,

    // bubbleable
    key: Key,
    text: []u8,
    close_popup: ClosePopup,
    scroll_drag: ScrollDrag,
    scroll_to: ScrollTo,
    scroll_propogate: ScrollPropogate,
},
```

To something more like this, in order to make `@TypeOf(Event.evt)` more accessible 

```zig
const Event = @This();

event_data: EventData,
metadata: struct {
    handled: bool = false,
    focus_windowId: ?u32 = null,
    focus_widgetId: ?u32 = null,
    // num increments withing a frame, used in focusRemainingEvents
    num: u16 = 0,
} = .{},

const EventData = union(enum) {
    // non-bubbleable
    mouse: Mouse,

    // bubbleable
    key: Key,
    text: []u8,
    close_popup: ClosePopup,
    scroll_drag: ScrollDrag,
    scroll_to: ScrollTo,
    scroll_propogate: ScrollPropogate,
};
```

**Comment by VisenDev** [comment]
If we choose not to process all raylib event data into an array of Events - then this proposal is not as relevant

**Comment by david-vanderson** [comment]
This is tough.  I would love a better API for events, but there is a decent amount of logic inside the `addEventX` functions that's all internal to dvui (tracking focus, debugging).

Maybe a different strategy would be to parse the raylib stuff and all the `addEventX` functions, and then iterate over the dvui.events?  But for the ontop stuff, I would expect the app to already be processing all the raylib events right?  So they would already have some kind of internal RaylibEvent?

Let me merge what you have and then I'll modify it according to my thoughts, and then we can compare.

**Comment by VisenDev** [comment]
> This is tough. I would love a better API for events, but there is a decent amount of logic inside the `addEventX` functions that's all internal to dvui (tracking focus, debugging).

Yes, the proposed approach would look like this

```zig
    pub fn addEvent(self: *Self, event: dvui.Event.EventData) !bool {
          switch(event) {
              .mouse => {
                   //mouse debugging, etc
              },
              .key => {
                  //key debugging, etc
              }
            }
            try self.events.append(.{.event_data = event, .metadata = .{...}};
     }
```

But if there is a lot more done in each of those functions than I realized it makes sense to keep them separate

**Comment by david-vanderson** [comment]
The splitting of the dvui-internal event datastructure members is pretty interesting.  Let's keep this idea in our back pocket for a while.  We are learning a lot from adding the raylib backend - a decent plan would be to see how you end up using it in practice for a while.
